# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer\image_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ui.components.scaled_label import ScaledPixmapLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 420)
        MainWindow.setMaximumSize(QtCore.QSize(600, 420))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.header_frame.setStyleSheet("background-color:rgb(100, 15, 200);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_frame = QtWidgets.QFrame(self.header_frame)
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.title_frame)
        self.verticalLayout_2.setContentsMargins(20, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name = QtWidgets.QLabel(self.title_frame)
        self.name.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setStyleSheet("color: rgb(255, 255, 255);")
        self.name.setScaledContents(True)
        self.name.setWordWrap(True)
        self.name.setOpenExternalLinks(True)
        self.name.setObjectName("name")
        self.verticalLayout_2.addWidget(self.name)
        self.horizontalLayout.addWidget(self.title_frame, 0, QtCore.Qt.AlignLeft)
        self.window_btns = QtWidgets.QFrame(self.header_frame)
        self.window_btns.setMaximumSize(QtCore.QSize(130, 16777215))
        self.window_btns.setStyleSheet("background-color: rgb(100, 15, 200);")
        self.window_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.window_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_btns.setObjectName("window_btns")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.window_btns)
        self.horizontalLayout_2.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.refresh_btn = QtWidgets.QPushButton(self.window_btns)
        self.refresh_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refresh_btn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(100, 15, 200);\n"
"    border-radius: 5px;\n"
"    padding: 3px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(70, 100, 198);\n"
"}")
        self.refresh_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_btn.setIcon(icon)
        self.refresh_btn.setIconSize(QtCore.QSize(24, 24))
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout_2.addWidget(self.refresh_btn)
        self.next_btn = QtWidgets.QPushButton(self.window_btns)
        self.next_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_btn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(100, 15, 200);\n"
"    border-radius: 5px;\n"
"    padding: 3px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(70, 100, 198);\n"
"}")
        self.next_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_btn.setIcon(icon1)
        self.next_btn.setIconSize(QtCore.QSize(24, 24))
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout_2.addWidget(self.next_btn)
        self.close_btn = QtWidgets.QPushButton(self.window_btns)
        self.close_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_btn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(100, 15, 200);\n"
"    border-radius: 5px;\n"
"    padding: 3px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgba(255, 6, 6, 150);\n"
"}")
        self.close_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/win_nav/window-close-button-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon2)
        self.close_btn.setIconSize(QtCore.QSize(24, 24))
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_2.addWidget(self.close_btn)
        self.horizontalLayout.addWidget(self.window_btns, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.header_frame)
        self.body_frame = QtWidgets.QFrame(self.centralwidget)
        self.body_frame.setStyleSheet("background-color:rgb(244, 244, 244);")
        self.body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body_frame.setObjectName("body_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.body_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.photo = ScaledPixmapLabel(self.body_frame)
        self.photo.setMaximumSize(QtCore.QSize(600, 420))
        self.photo.setText("")
        self.photo.setObjectName("photo")
        self.verticalLayout_3.addWidget(self.photo)
        self.verticalLayout.addWidget(self.body_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name.setText(_translate("MainWindow", ""))
