# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(693, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(100, 15, 200);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_header = QtWidgets.QFrame(self.centralwidget)
        self.main_header.setMaximumSize(QtCore.QSize(16777215, 35))
        self.main_header.setStyleSheet("background-color: rgb(100, 15, 200);")
        self.main_header.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.main_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_header.setObjectName("main_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.title_bar_container = QtWidgets.QFrame(self.main_header)
        self.title_bar_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar_container.setObjectName("title_bar_container")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.title_bar_container)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.left_menu_toggle = QtWidgets.QFrame(self.title_bar_container)
        self.left_menu_toggle.setMaximumSize(QtCore.QSize(48, 16777215))
        self.left_menu_toggle.setStyleSheet("margin: 0 2px;\n"
"padding: 0;")
        self.left_menu_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_menu_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_toggle.setObjectName("left_menu_toggle")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.left_menu_toggle)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menu_toggle_btn = QtWidgets.QPushButton(self.left_menu_toggle)
        self.menu_toggle_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.menu_toggle_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_toggle_btn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(100, 15, 200);\n"
"    border-radius: 5px;\n"
"    padding: 3px 6px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 0, 255);\n"
"}")
        self.menu_toggle_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/burger-bar-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_toggle_btn.setIcon(icon)
        self.menu_toggle_btn.setIconSize(QtCore.QSize(24, 24))
        self.menu_toggle_btn.setFlat(True)
        self.menu_toggle_btn.setObjectName("menu_toggle_btn")
        self.horizontalLayout_4.addWidget(self.menu_toggle_btn)
        self.horizontalLayout_5.addWidget(self.left_menu_toggle)
        self.title_label = QtWidgets.QLabel(self.title_bar_container)
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout_5.addWidget(self.title_label)
        self.horizontalLayout_2.addWidget(self.title_bar_container)
        self.window_btns = QtWidgets.QFrame(self.main_header)
        self.window_btns.setMaximumSize(QtCore.QSize(150, 16777215))
        self.window_btns.setStyleSheet("background-color: rgb(100, 15, 200);")
        self.window_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.window_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_btns.setObjectName("window_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.window_btns)
        self.horizontalLayout_3.setContentsMargins(0, 0, 8, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minimize_btn = QtWidgets.QPushButton(self.window_btns)
        self.minimize_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimize_btn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(100, 15, 200);\n"
"    border-radius: 5px;\n"
"    padding: 3px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 0, 255);\n"
"}")
        self.minimize_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/win_nav/window_minimize-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_btn.setIcon(icon1)
        self.minimize_btn.setIconSize(QtCore.QSize(24, 24))
        self.minimize_btn.setObjectName("minimize_btn")
        self.horizontalLayout_3.addWidget(self.minimize_btn)
        self.restore_btn = QtWidgets.QPushButton(self.window_btns)
        self.restore_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.restore_btn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(100, 15, 200);\n"
"    border-radius: 5px;\n"
"    padding: 3px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 0, 255);\n"
"}")
        self.restore_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/win_nav/window-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restore_btn.setIcon(icon2)
        self.restore_btn.setIconSize(QtCore.QSize(24, 24))
        self.restore_btn.setObjectName("restore_btn")
        self.horizontalLayout_3.addWidget(self.restore_btn)
        self.close_btn = QtWidgets.QPushButton(self.window_btns)
        self.close_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_btn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(100, 15, 200);\n"
"    border-radius: 5px;\n"
"    padding: 3px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgba(255, 6, 6, 150);\n"
"}")
        self.close_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/win_nav/window-close-button-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon3)
        self.close_btn.setIconSize(QtCore.QSize(24, 24))
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_3.addWidget(self.close_btn)
        self.horizontalLayout_2.addWidget(self.window_btns, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.main_header)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setStyleSheet("")
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_side_menu = QtWidgets.QFrame(self.main_body)
        self.left_side_menu.setMinimumSize(QtCore.QSize(47, 0))
        self.left_side_menu.setMaximumSize(QtCore.QSize(40, 16777215))
        self.left_side_menu.setStyleSheet("\n"
"QPushButton {\n"
"    padding: 8px 0 8px 10px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 0, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(96, 0, 144);\n"
"}\n"
"\n"
"QFrame {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.0625, x2:0, y2:1, stop:0 rgba(100, 15, 200, 255), stop:1 rgba(187, 87, 255, 255));\n"
"padding-top: 10px;\n"
"padding-bottom: 10px;\n"
"}\n"
"\n"
"")
        self.left_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_side_menu.setObjectName("left_side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_side_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home_page_btn = QtWidgets.QPushButton(self.left_side_menu)
        self.home_page_btn.setMinimumSize(QtCore.QSize(115, 46))
        self.home_page_btn.setMaximumSize(QtCore.QSize(115, 16777215))
        self.home_page_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_page_btn.setStyleSheet("QPushButton {\n"
"image: url(:/icons/icons/home.png);\n"
"image-position: left;\n"
"text-align: center;\n"
"background-color: transparent;\n"
"}\n"
"\n"
"[active=\"true\"] {\n"
"     image: url(:/icons/icons/home _dark.png);\n"
"     background-color: rgb(244, 244, 244);\n"
"    color: black;\n"
"}")
        self.home_page_btn.setProperty("active", True)
        self.home_page_btn.setObjectName("home_page_btn")
        self.verticalLayout_2.addWidget(self.home_page_btn)
        self.experiments_page_btn = QtWidgets.QPushButton(self.left_side_menu)
        self.experiments_page_btn.setMinimumSize(QtCore.QSize(115, 46))
        self.experiments_page_btn.setMaximumSize(QtCore.QSize(115, 16777215))
        self.experiments_page_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.experiments_page_btn.setStyleSheet("QPushButton {\n"
"image: url(:/icons/icons/experiment.png);\n"
"image-position: left;\n"
"text-align: center;\n"
"background-color: transparent;\n"
"}\n"
"\n"
"[active=\"true\"] {\n"
"     image: url(:/icons/icons/experiment_dark.png);\n"
"     background-color: rgb(244, 244, 244);\n"
"        color: black;\n"
"}")
        self.experiments_page_btn.setProperty("active", False)
        self.experiments_page_btn.setObjectName("experiments_page_btn")
        self.verticalLayout_2.addWidget(self.experiments_page_btn)
        self.settings_page_btn = QtWidgets.QPushButton(self.left_side_menu)
        self.settings_page_btn.setMinimumSize(QtCore.QSize(115, 46))
        self.settings_page_btn.setMaximumSize(QtCore.QSize(115, 16777215))
        self.settings_page_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings_page_btn.setStyleSheet("QPushButton {\n"
"image: url(:/icons/icons/settings.png);\n"
"image-position: left;\n"
"text-align: center;\n"
"background-color: transparent;\n"
"}\n"
"\n"
"[active=\"true\"] {\n"
"     image: url(:/icons/icons/settings_dark.png);\n"
"     background-color: rgb(244, 244, 244);\n"
"        color: black;\n"
"}")
        self.settings_page_btn.setProperty("active", False)
        self.settings_page_btn.setObjectName("settings_page_btn")
        self.verticalLayout_2.addWidget(self.settings_page_btn, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.left_side_menu)
        self.center_items = QtWidgets.QFrame(self.main_body)
        self.center_items.setStyleSheet("background-color: rgb(244, 244, 244);")
        self.center_items.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center_items.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_items.setObjectName("center_items")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.center_items)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.center_items)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setStyleSheet("")
        self.home_page.setObjectName("home_page")
        self.layout_121 = QtWidgets.QVBoxLayout(self.home_page)
        self.layout_121.setContentsMargins(0, 0, 0, 0)
        self.layout_121.setSpacing(0)
        self.layout_121.setObjectName("layout_121")
        self.scrollArea = QtWidgets.QScrollArea(self.home_page)
        self.scrollArea.setStyleSheet("border: none;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 642, 561))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.home_page_layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.home_page_layout.setObjectName("home_page_layout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.layout_121.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.home_page)
        self.experiment_page = QtWidgets.QWidget()
        self.experiment_page.setObjectName("experiment_page")
        self.label_2 = QtWidgets.QLabel(self.experiment_page)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 441, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.experiment_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.label_3 = QtWidgets.QLabel(self.settings_page)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.settings_page)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.center_items)
        self.verticalLayout.addWidget(self.main_body)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "Furniture Detection by Sayurbai I."))
        self.home_page_btn.setText(_translate("MainWindow", "HOME"))
        self.experiments_page_btn.setText(_translate("MainWindow", "           EXPERIMENT"))
        self.settings_page_btn.setText(_translate("MainWindow", "       SETTINGS"))
        self.label_2.setText(_translate("MainWindow", "EXPERIMENTS PAGE"))
        self.label_3.setText(_translate("MainWindow", "SETTINGS PAGE"))
