# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer\components\primary_btn.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class PrimaryBtn(object):
    def __init__(self, parent, text='PushButton'):
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.MinimumExpanding,QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(parent if isinstance(parent, QtWidgets.QWidget) else None)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(250, 35))
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color: transparent;\n"
"border: 2px solid #007bff;\n"
"border-radius: 5px;\n"
"color: #007bff;\n"
"padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #007bff;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(3, 97, 190);\n"
"color: rgb(3, 97, 190);\n"
"color: rgb(238, 238, 238);\n"
"}")
        self.pushButton.setText(text)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        if isinstance(parent, QtWidgets.QLayout):
            parent.addLayout(self.horizontalLayout_2)