# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer\components\select.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Select(object):
    def __init__(self, parent, label_text):
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame = QtWidgets.QFrame()
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setText(label_text)
        self.label.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setEnabled(True)
        self.comboBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setStyleSheet("QComboBox {\n"
"border: 1px solid #ced4da;\n"
"border-radius: 4px;\n"
"padding: 5px 0 5px 10px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"border: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"image: url(:/icons/icons/down-arrow.png);\n"
"width: 12px;\n"
"height: 12px;\n"
"margin-right: 12px;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"border: 4px solid #c2dbfe;\n"
"}\n"
"\n"
"QComboBox QListView {\n"
"font-size: 12px;\n"
"border: 1px solid rgba(0, 0, 0, 10%);\n"
"padding: 5px;\n"
"background-color: rgb(255, 255, 255);\n"
"outline: 0px;\n"
"}\n"
"\n"
"#comboBox QListView::item:hover{\n"
"padding-left: 10px;\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"/*QComboBox QListView::item:hover {\n"
"background-color: rgb(30, 144, 255);\n"
"}*/\n"
"\n"
"QComboBox QListView::item:selected {\n"
"background-color: rgb(30, 144, 255);\n"
"}\n"
"")
        self.comboBox.setIconSize(QtCore.QSize(20, 20))
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.horizontalLayout.addWidget(self.frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        parent.addLayout(self.horizontalLayout)
